qemu-test: show some system information on failing tests
Signed-off-by: Jan Luebbe <jlu@pengutronix.de>

diff --git a/qemu-test-init b/qemu-test-init
--- a/qemu-test-init
+++ b/qemu-test-init
@@ -64,6 +64,10 @@ fi
 if make check; then
   touch qemu-test-ok
 else
-  cat test-suite.log
+  cat test-suite.log || true
+  # show system status on error
+  mount || true
+  df -h || true
+  free || true
 fi
 echo o > /proc/sysrq-trigger
